#### Agreement

#### StateMachine
p2p_port=34000

# Either contact or initial_membership
initial_membership=asd-1:34000,asd-2:34001,asd-3:34002
address=0.0.0.0

#### App
server_port=35000

##### General
interface=lo
replication_strategy=SMR
