#### Agreement

#### StateMachine
p2p_port=34000

# When joining after
contact=127.0.0.1:34000

# Either contact or initial_membership

#### App
server_port=35000

##### General
interface=lo
replication_strategy=ABD
